# Generated by Django 6.0.4 on 2026-05-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
