# Generated by Django 6.0.4 on 2026-05-10 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image1_url_product_image2_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_hex',
            field=models.CharField(blank=True, help_text='Hex code, e.g. #FF0000', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='parent_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='products.product'),
        ),
    ]
