# Generated by Django 5.2.14 on 2026-06-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='order_updates_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
