# Generated by Django 5.2.14 on 2026-06-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_order_updates_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_deleted_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
